version = "0.1.0"
description = "JupyterLab on Tanzu Platform for Cloud Foundry with uv"
requires-python = ">=3.11"
dependencies = [
    "jupyterlab==4.2.5",
    "jupyterlab-git==0.51.2",
    "notebook",
    "ipykernel",
    "python-dotenv",
    "ipywidgets",
    "requests",
    "openai",
    "gradio",
    "langchain",
    "langchain-openai",
    "langchain-experimental",
    "langchain-chroma",
    "langchain[docarray]",
    "datasets",
    "matplotlib",
    "google-generativeai",
    "anthropic",
    "unstructured",
    "pydub",
    "modal",
    "ollama",
    "langgraph-checkpoint-sqlite",
    "tavily-python",
    "langchain-mcp-adapters",
    "matplotlib",
    "unstructured",
    "pydub",
    "modal",
    "trulens>=2.3.1",
    "trulens-apps-langchain>=2.3.1",
    "trulens-providers-openai>=2.2.2",
    "langchain-postgres>=0.0.15",
    "psycopg2>=2.9.10",
    "trulens-providers-litellm>=2.3.1",
    "langchain-nomic>=0.1.4",
    "cfenv>=0.5.3",
    "langgraph-prebuilt>=0.6.4",
    "langgraph>=0.6.7",
]

[tool.uv]
dev-dependencies = []
